name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: sudo apt-get -y install ninja
    - uses: actions/cache@v1
      id: llvm-cache
      with:
        path: llvm-project
    - name: Initialize LLVM
      if: steps.llvm-cache.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/llvm/llvm-project
        mkdir llvm-build || true
        cd llvm-build
        cmake -G Ninja -DLLVM_ENABLE_PROJECTS="clang;lld" -DCMAKE_BUILD_TYPE=Release ../llvm-project/llvm
    - name: Update LLVM
      run: git -C llvm-project pull
    - uses: actions/cache@v1
      id: llvm-build-cache
      with:
        path: llvm-build
        key: ${{ runner.os }}
    - name: Build LLVM
      run: |
        cd llvm-build
        ninja

